name: Gradle Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew build
      - uses: codecov/codecov-action@v4
        with:
          files: ./build/reports/kover/report.xml
